import { NextPage } from 'next';
import Head from 'next/head';

const Product: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='min-h-screen'>
				<h2>Product 555</h2>
			</main>
		</>
	);
};

export default Product;
