import type { NextPage } from 'next';
import Head from 'next/head';
import Featured from '../components/Featured';
import Hero from '../components/Hero';
import NewProducts from '../components/NewProducts';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <>
        <Hero />
        <NewProducts />
        <Featured />
      </>
    </>
  );
};

export default Home;
