import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Banner from '../components/Banner';
import Featured from '../components/Featured';
import Hero from '../components/Hero';
import NewArrivals from '../components/NewArrivals';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='min-h-screen'>
        <Banner />
        <Hero />
        <NewArrivals />
        <Featured />
      </main>
    </>
  );
};

export default Home;
